# Generated by Django 3.2 on 2023-11-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBD', '0002_auto_20231128_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='id_clientes',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='id_tipoAlquiler',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.RemoveField(
            model_name='clienteempleado',
            name='id_clientes',
        ),
        migrations.RemoveField(
            model_name='clienteempleado',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='clienteorden',
            name='id_clientes',
        ),
        migrations.RemoveField(
            model_name='clienteorden',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='detallealquiler',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_clientes',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='facturaempleado',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='facturaempleado',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id_nombreItem',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='id_item',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='id_orden',
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.DeleteModel(
            name='ClienteEmpleado',
        ),
        migrations.DeleteModel(
            name='ClienteOrden',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='DetalleAlquiler',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='FacturaEmpleado',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
        migrations.DeleteModel(
            name='NombreItem',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='TipoAlquiler',
        ),
    ]
