# Generated by Django 3.2 on 2023-11-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBD', '0003_auto_20231128_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
